### ISSUE TITLE
Typo in ENV file for the CONTAINER_NAME

### ISSUE THREAD

**Issue by zeromancer1972** [HCL-TECH-SOFTWARE/domino-keep-docs#11]
**Type**
[x ] Typo
[ ] Broken Link
[ ] Inaccurate
[ ] Incomplete

**Describe the error**
In the ENV sample file there is a typo for the variable CONTAINER_NAME - looks like someone typed "over" the existing name in capitals. Same for SERVERSETUP_EXISTINGSERVER_HOSTNAMEORIP

**Page**
https://opensource.hcltechsw.com/domino-keep-docs/assets/downloads/sample.env

**To Reproduce**
n/a

**Expected behavior**
Line 18 should start with `CONTAINER_NAME`

**Comment by paulswithers** [comment]
There's also another typo. This should be "SERVERSETUP_EXISTINGSERVER_HOSTNAMEORIP" rather than SERVERSETUP_EXISTINGSERVER_HOSTNAMEORIPadmin_ip

![image](https://user-images.githubusercontent.com/3721367/124153325-35556e80-da8c-11eb-9d48-d2b9aadb1593.png)

**Comment by Stwissel** [comment]
Fixed in #15
