### ISSUE TITLE
[BUG] Vertex instead of Vert.x

### ISSUE THREAD

**Issue by paulswithers** [HCL-TECH-SOFTWARE/domino-keep-docs#21]
**Type**
[x] Typo
[ ] Broken Link
[ ] Inaccurate
[ ] Incomplete

**Describe the error**
There are a couple of places where documentation says Vertex instead of Vert.x

**Page**
https://opensource.hcltechsw.com/domino-keep-docs/installconfig/configuration/security/configjson/
https://opensource.hcltechsw.com/domino-keep-docs/installconfig/configuration/parameters/

**To Reproduce**
1. Go to Keep docs and search "Vertex"
2. See references

**Expected behavior**

**Screenshots**
If possible, add screenshots to help explain your problem.

**Additional context**

**Comment by Stwissel** [comment]
closed by #23
