### ISSUE TITLE
[BUG] Broken link on IDP config Page

### ISSUE THREAD

**Issue by BerndGewehr** [HCL-TECH-SOFTWARE/domino-keep-docs#41]
**Type**
[ ] Typo
[X ] Broken Link
[ ] Inaccurate
[ ] Incomplete

**Describe the error**
The example keycloak configuration link is broken

**Page**
Link to page
https://opensource.hcltechsw.com/domino-keep-docs/installconfig/configuration/security/configuringIdentityProvider/

**To Reproduce**
1. klick on keycloak in "Check out the Keycloak example configuration"
2. See error

**Expected behavior**
Page opens correctly

**Comment by BerndGewehr** [comment]
Also broken on same page:

Roll your own in 
![image](https://user-images.githubusercontent.com/21081707/136353751-326806f7-5f55-4ee9-b021-fc71d43eb2ba.png)

target: 
https://opensource.hcltechsw.com/domino-keep-docs/installconfig/configuration/security/configuringIdentityProvider/customIdp

Page does not exist.

**Comment by rwilkins108** [comment]
Confirmed fixed
